List<dynamic> channels = [
  {
    "id": "19",
    "title": "BEIN SPORTS 4K",
    "image": "uploads/bein4k.png",
    "streamname": "bein4k",
    "type": "0",
    "vorder": "1",
    "enable": "1",
    "cat": "Sports",
    "color": "#663399",
    "app": "bein1",
    "epg": "5"
  },
  {
    "id": "20",
    "title": "BEIN SPORTS 1HD",
    "image": "uploads/bein1.png",
    "streamname": "1",
    "type": "1",
    "vorder": "1",
    "enable": "1",
    "cat": "Sports",
    "color": "#663399",
    "app": "bein1",
    "epg": "5"
  },
  {
    "id": "21",
    "title": "BEIN SPORTS 2HD",
    "image": "uploads/bein2.png",
    "streamname": "2",
    "type": "1",
    "vorder": "2",
    "enable": "1",
    "cat": "Sports",
    "color": "#663399",
    "app": "bein1",
    "epg": "6"
  },
  {
    "id": "22",
    "title": "BEIN SPORTS 3HD",
    "image": "uploads/bein3.png",
    "streamname": "3",
    "type": "1",
    "vorder": "3",
    "enable": "1",
    "cat": "Sports",
    "color": "#663399",
    "app": "bein1",
    "epg": "7"
  },
  {
    "id": "23",
    "title": "BEIN SPORTS 4HD",
    "image": "uploads/bein4.png",
    "streamname": "4",
    "type": "1",
    "vorder": "4",
    "enable": "1",
    "cat": "Sports",
    "color": "#663399",
    "app": "bein1",
    "epg": "8"
  },
  {
    "id": "24",
    "title": "BEIN SPORTS 5HD",
    "image": "uploads/bein5.png",
    "streamname": "5",
    "type": "1",
    "vorder": "5",
    "enable": "1",
    "cat": "Sports",
    "color": "#663399",
    "app": "bein1",
    "epg": "9"
  },
  {
    "id": "178",
    "title": "ON SPORT HD",
    "image": "uploads/onsports.png",
    "streamname": "ons",
    "type": "0",
    "vorder": "12",
    "enable": "1",
    "cat": "Sports",
    "color": "",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "26",
    "title": "OSN YAHALA HD",
    "image": "uploads/osnyahala.png",
    "streamname": "7",
    "type": "1",
    "vorder": "13",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#ff0000",
    "app": "live",
    "epg": "26"
  },
  {
    "id": "29",
    "title": "OSN YAHALA AL OULA",
    "image": "uploads/osnyahalao.png",
    "streamname": "9",
    "type": "1",
    "vorder": "13",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#ff0000",
    "app": "live",
    "epg": "26"
  },
  {
    "id": "152",
    "title": "IRAQIA NEWS",
    "image": "uploads/iqn.png",
    "streamname": "iqn",
    "type": "0",
    "vorder": "13",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#ff0000",
    "app": "nile",
    "epg": "26"
  },
  {
    "id": "28",
    "title": "PLANET EARTH HD",
    "image": "uploads/planetearth.png",
    "streamname": "5",
    "type": "1",
    "vorder": "14",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#9c9c9c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "30",
    "title": "DISCOVERY HD",
    "image": "uploads/discoveryhd.png",
    "streamname": "10",
    "type": "1",
    "vorder": "14",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#2c6eaa",
    "app": "live",
    "epg": "41"
  },
  {
    "id": "25",
    "title": "OSN MOVIES FIRST",
    "image": "uploads/osnmoviesfirst.png",
    "streamname": "6",
    "type": "1",
    "vorder": "15",
    "enable": "1",
    "cat": "Movies",
    "color": "#e67300",
    "app": "live",
    "epg": "33"
  },
  {
    "id": "209",
    "title": "OSN MOVIES KIDS",
    "image": "uploads/osnmovieskids.png",
    "streamname": "112",
    "type": "1",
    "vorder": "15",
    "enable": "1",
    "cat": "Movies",
    "color": "#663399",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "27",
    "title": "NAT GEO WILD HD",
    "image": "uploads/NatGeoWild.png",
    "streamname": "8",
    "type": "1",
    "vorder": "17",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#febd23",
    "app": "live",
    "epg": "27"
  },
  {
    "id": "32",
    "title": "ANIMAL PLANET HD",
    "image": "uploads/AnimalPlant.png",
    "streamname": "12",
    "type": "1",
    "vorder": "18",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#22CA4E",
    "app": "live",
    "epg": "29"
  },
  {
    "id": "33",
    "title": "TRAVEL CHANNEL",
    "image": "uploads/travel.png",
    "streamname": "13",
    "type": "1",
    "vorder": "19",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#0CB3E8",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "34",
    "title": "DISCOVERY SCIENCE HD",
    "image": "uploads/discoverysc.png",
    "streamname": "14",
    "type": "1",
    "vorder": "20",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#febd23",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "35",
    "title": "FIX & FOXI",
    "image": "uploads/fix.png",
    "streamname": "15",
    "type": "1",
    "vorder": "22",
    "enable": "1",
    "cat": "Kids",
    "color": "#ff0000",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "97",
    "title": "itv Choice",
    "image": "uploads/itv.png",
    "streamname": "78",
    "type": "1",
    "vorder": "23",
    "enable": "1",
    "cat": "Movies",
    "color": "#9c9c9c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "36",
    "title": "STEREO MUSIC",
    "image": "uploads/stereo.png",
    "streamname": "16",
    "type": "1",
    "vorder": "24",
    "enable": "1",
    "cat": "Music",
    "color": "#22CA4E",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "158",
    "title": "FATAFEAT",
    "image": "uploads/fatafeat.png",
    "streamname": "19",
    "type": "1",
    "vorder": "24",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#ff0000",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "184",
    "title": "FOX REWAYAT HD",
    "image": "uploads/foxr.png",
    "streamname": "99",
    "type": "1",
    "vorder": "31",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#9c9c9c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "187",
    "title": "FOX CRIME HD",
    "image": "uploads/foxcrime.png",
    "streamname": "104",
    "type": "1",
    "vorder": "32",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#0CB3E8",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "164",
    "title": "AD SPORTS 1",
    "image": "uploads/ads1.png",
    "streamname": "ad1",
    "type": "0",
    "vorder": "34",
    "enable": "1",
    "cat": "Sports",
    "color": "#8f8f8f",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "165",
    "title": "AD SPORTS 2",
    "image": "uploads/ads2.png",
    "streamname": "ad2",
    "type": "0",
    "vorder": "35",
    "enable": "1",
    "cat": "Sports",
    "color": "#8f8f8f",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "113",
    "title": "AD DRAMA HD",
    "image": "uploads/addrama.png",
    "streamname": "add",
    "type": "0",
    "vorder": "38",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#663399",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "157",
    "title": "Dijla TV",
    "image": "uploads/dijla.png",
    "streamname": "dij",
    "type": "0",
    "vorder": "40",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#663399",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "86",
    "title": "MBC+ DRAMA",
    "image": "uploads/mbcdramaplus.png",
    "streamname": "18",
    "type": "1",
    "vorder": "51",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#9c9c9c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "64",
    "title": "MBC+ VARIETY",
    "image": "uploads/mbcv.png",
    "streamname": "96",
    "type": "1",
    "vorder": "52",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#e0226c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "87",
    "title": "BARAEEM",
    "image": "uploads/baraem.png",
    "streamname": "17",
    "type": "1",
    "vorder": "52",
    "enable": "1",
    "cat": "Kids",
    "color": "#9c9c9c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "76",
    "title": "MBC",
    "image": "uploads/mbc.png",
    "streamname": "mbc1.stream_360p",
    "type": "0",
    "vorder": "53",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#9c9c9c",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "79",
    "title": "MBC 4",
    "image": "uploads/mbc4.png",
    "streamname": "mbc4-1.stream_360p",
    "type": "0",
    "vorder": "56",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#9900cc",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "118",
    "title": "ART Hekayat",
    "image": "uploads/arthikayat.png",
    "streamname": "24",
    "type": "0",
    "vorder": "70",
    "enable": "1",
    "cat": "Movies",
    "color": "#9c9c9c",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "56",
    "title": "GULLI",
    "image": "uploads/gulli.png",
    "streamname": "44",
    "type": "1",
    "vorder": "78",
    "enable": "1",
    "cat": "Kids",
    "color": "#f0cfba",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "179",
    "title": "ON TV HD",
    "image": "uploads/ontv.png",
    "streamname": "ontv",
    "type": "0",
    "vorder": "100",
    "enable": "1",
    "cat": "Entertainment",
    "color": "",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "180",
    "title": "DMC Drama",
    "image": "uploads/dmcdrama.png",
    "streamname": "dmcdrama",
    "type": "0",
    "vorder": "100",
    "enable": "1",
    "cat": "Entertainment",
    "color": "",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "181",
    "title": "Abu Dhabi TV",
    "image": "uploads/adtv.png",
    "streamname": "sv1",
    "type": "0",
    "vorder": "100",
    "enable": "1",
    "cat": "Entertainment",
    "color": "",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "173",
    "title": "ALKASS 1 HD",
    "image": "uploads/alkass1.png",
    "streamname": "kass1",
    "type": "0",
    "vorder": "115",
    "enable": "1",
    "cat": "Sports",
    "color": "",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "138",
    "title": "YAS SPORTS",
    "image": "uploads/yas.png",
    "streamname": "yas",
    "type": "0",
    "vorder": "116",
    "enable": "1",
    "cat": "Sports",
    "color": "",
    "app": "nile",
    "epg": "0"
  },
  // {
  //   "id": "174",
  //   "title": "Al-Arabiya",
  //   "image": "uploads/arabiya.png",
  //   "streamname": "al-arabiya",
  //   "type": "0",
  //   "vorder": "116",
  //   "enable": "1",
  //   "cat": "Entertainment",
  //   "color": "",
  //   "app": "nile",
  //   "epg": "0"
  // },
  {
    "id": "177",
    "title": "Cinema",
    "image": "uploads/cinema.png",
    "streamname": "cima",
    "type": "0",
    "vorder": "134",
    "enable": "1",
    "cat": "Movies",
    "color": "#8f8f8f",
    "app": "live",
    "epg": "0"
  },
  {
    "id": "69",
    "title": "AL-RASHEED",
    "image": "uploads/rasheed.png",
    "streamname": "alrasheed1.stream_360p",
    "type": "0",
    "vorder": "148",
    "enable": "1",
    "cat": "Entertainment",
    "color": "#9900cc",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "70",
    "title": "Aghani TV",
    "image": "uploads/mtvl.png",
    "streamname": "music-alremas1.stream_360p",
    "type": "0",
    "vorder": "149",
    "enable": "1",
    "cat": "Music",
    "color": "#9900cc",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "190",
    "title": "ZEE Alwan",
    "image": "uploads/zeeaflam.png",
    "streamname": "zeealwan",
    "type": "0",
    "vorder": "154",
    "enable": "1",
    "cat": "Movies",
    "color": "#4d0000",
    "app": "nile",
    "epg": "0"
  },
  {
    "id": "84",
    "title": "ROTANA",
    "image": "uploads/rotana.png",
    "streamname": "rotana1.stream_360p",
    "type": "0",
    "vorder": "163",
    "enable": "1",
    "cat": "Music",
    "color": "#006600",
    "app": "nile",
    "epg": "0"
  }
];
